stages:
  import:
    cmd: python src/data/import_raw_data.py
    deps:
    - src/data/import_raw_data.py
    outs:
    - data/raw
  prepare:
    cmd: python src/data/make_dataset.py
    deps:
    - data/raw
    - src/data/make_dataset.py
    outs:
    - data/preprocessed
  normalise:
    cmd: python src/features/build_features.py
    deps:
    - data/preprocessed
    - src/features/build_features.py
    outs:
    - data/processed
  gridsearch:
    cmd: python src/models/search_model.py
    deps:
    - data/processed
    - src/models/search_model.py
    outs:
    - models/best_model.pkl
  train:
    cmd: python src/models/train_model.py
    deps:
    - models/best_model.pkl
    - src/models/train_model.py
    outs:
    - models/trained_model.pkl
  evaluer:
    cmd: python src/models/evaluate_model.py
    deps:
    - models/trained_model.pkl
    - src/models/evaluate_model.py
    outs:
    - data/predictions
    metrics:
    - metrics/scores.json:
        cache: false
